import { InboundQueue, QueueSectionDef } from './types';

/**
 * INBOUND QUEUE FIELD MODEL — 37 fields.
 *
 * Queue fields deliberately DO NOT inherit from the campaign. Inbound music-on-hold,
 * inbound ring timeout and inbound SMS templates are genuinely different values from
 * their outbound counterparts. Where a field is twinned with a campaign one, `cmp`
 * names the campaign field so the UI can show it as a read-only reference beside the
 * input. It is a reference, never a copy: nothing is ever written from one to the other.
 */

const q = (x: Record<string, unknown>) => x as unknown as InboundQueue;

export const QUEUE_SECTIONS: QueueSectionDef[] = [
  {
    id: 'qbasics',
    title: 'Queue basics',
    sub: 'Name it, and say which inbound numbers land here.',
    fields: [
      { id: 'name', label: 'Queue name', kind: 'text', req: true, ph: 'e.g. WEST HFC collections' },
      { id: 'desc', label: 'Description', kind: 'text' },
      {
        id: 'dids',
        label: 'Inbound numbers routed here',
        kind: 'chips',
        req: true,
        help: 'This is what separates one queue from another on the same campaign. A number can only point at one queue.',
      },
      {
        id: 'strategy',
        label: 'Ring strategy',
        kind: 'select',
        req: true,
        opts: ['Longest wait time', 'Fewest calls', 'Random'],
        help: 'Which free agent gets the call first.',
      },
      {
        id: 'queueTimeout',
        label: 'Queue timeout (sec)',
        kind: 'number',
        req: true,
        help: 'How long a caller waits before failover.',
      },
      {
        id: 'agentRingTimeout',
        label: 'Agent ring timeout (sec)',
        kind: 'number',
        req: true,
        cmp: 'ringTimeout',
        help: 'How long one agent rings before trying the next.',
      },
      {
        id: 'transferCode',
        label: 'Transfer code',
        kind: 'text',
        help: 'Short code agents dial to send a call here.',
      },
      { id: 'intercomId', label: 'Intercom ID', kind: 'text' },
    ],
  },
  {
    id: 'qagents',
    title: 'Agents',
    sub: 'Who answers calls in this queue.',
    fields: [{ id: '__agents', kind: 'agents' }],
  },
  {
    id: 'qfail',
    title: 'When nobody answers',
    sub: 'Where the call goes once the queue times out.',
    fields: [
      {
        id: 'failoverDest',
        label: 'Failover destination',
        kind: 'select',
        req: true,
        opts: ['Hangup', 'Voicemail', 'Another queue', 'External number', 'IVR'],
      },
      {
        id: 'failoverMusic',
        label: 'Failover recording',
        kind: 'select',
        opts: ['', 'Sorry we missed you', 'Try again later'],
      },
    ],
  },
  {
    id: 'qsticky',
    title: 'Sticky agent',
    sub: 'Send repeat callers back to the agent they spoke to.',
    fields: [
      {
        id: 'sticky',
        label: 'Sticky agent',
        kind: 'select',
        req: true,
        opts: ['No', 'Yes'],
        help: 'Routes a returning caller to their previous agent.',
      },
      {
        id: 'stickyTimeFormat',
        label: 'Remember for',
        kind: 'select',
        req: true,
        when: (x) => q(x).sticky === 'Yes',
        dependsOn: ['sticky'],
        opts: ['', 'Same day', '24 hours', '7 days', '30 days'],
      },
      {
        id: 'stickyFailover',
        label: 'If that agent is unavailable',
        kind: 'select',
        req: true,
        when: (x) => q(x).sticky === 'Yes',
        dependsOn: ['sticky'],
        opts: ['', 'Follow queue strategy', 'Hangup / drop call'],
      },
      {
        id: 'stickyFailoverRec',
        label: 'Sticky failover recording',
        kind: 'select',
        when: (x) => q(x).sticky === 'Yes',
        dependsOn: ['sticky'],
        opts: ['', 'Your agent is busy', 'Connecting you to another agent'],
      },
    ],
  },
  {
    id: 'qcaller',
    title: 'Caller experience',
    sub: 'What the caller hears while they wait.',
    fields: [
      {
        id: 'welcome',
        label: 'Welcome announcement',
        kind: 'select',
        opts: ['', 'Standard greeting', 'Recording disclosure'],
      },
      {
        id: 'moh',
        label: 'Music on hold',
        kind: 'select',
        opts: ['', 'Corporate loop', 'Regional instrumental'],
        cmp: 'moh',
      },
      { id: 'waitAnnounce', label: 'Announce expected wait', kind: 'toggle' },
      {
        id: 'waitRec',
        label: 'Wait announcement recording',
        kind: 'select',
        when: (x) => !!q(x).waitAnnounce,
        dependsOn: ['waitAnnounce'],
        opts: ['', 'Estimated wait (English)', 'Estimated wait (Hindi)'],
      },
      { id: 'positionAnnounce', label: 'Announce position in queue', kind: 'toggle' },
      {
        id: 'positionRec',
        label: 'Position announcement recording',
        kind: 'select',
        when: (x) => !!q(x).positionAnnounce,
        dependsOn: ['positionAnnounce'],
        opts: ['', 'You are number N (English)', 'You are number N (Hindi)'],
      },
      {
        id: 'queueLimit',
        label: 'Cap how many can wait',
        kind: 'toggle',
        help: 'Turns callers away once the queue is full.',
      },
      {
        id: 'maxCallers',
        label: 'Maximum callers waiting',
        kind: 'number',
        req: true,
        when: (x) => !!q(x).queueLimit,
        dependsOn: ['queueLimit'],
      },
      {
        id: 'limitAction',
        label: 'When the queue is full',
        kind: 'select',
        req: true,
        when: (x) => !!q(x).queueLimit,
        dependsOn: ['queueLimit'],
        opts: ['Hangup', 'Voicemail', 'External number'],
      },
      {
        id: 'repeatCaller',
        label: 'Flag repeat callers',
        kind: 'toggle',
        help: 'Alerts the agent that this caller has called before.',
      },
      {
        id: 'repeatDays',
        label: 'Count repeats within (days)',
        kind: 'select',
        req: true,
        when: (x) => !!q(x).repeatCaller,
        dependsOn: ['repeatCaller'],
        opts: ['', '1', '2', '3', '4', '5'],
      },
    ],
  },
  {
    id: 'qcallback',
    title: 'Callback',
    sub: 'Let callers hang up and be called back instead of waiting.',
    fields: [
      { id: 'callback', label: 'Offer a callback', kind: 'toggle' },
      {
        id: 'threshold',
        label: 'Offer it after (sec)',
        kind: 'number',
        req: true,
        when: (x) => !!q(x).callback,
        dependsOn: ['callback'],
        help: 'How long the caller waits before the offer is made.',
      },
      {
        id: 'dtmf',
        label: 'Key the caller presses',
        kind: 'text',
        req: true,
        when: (x) => !!q(x).callback,
        dependsOn: ['callback'],
        ph: '0-9',
      },
      {
        id: 'thresholdRec',
        label: 'Callback offer recording',
        kind: 'select',
        when: (x) => !!q(x).callback,
        dependsOn: ['callback'],
        opts: ['', 'Press 9 for a callback', 'We can call you back'],
      },
      {
        id: 'hangupRec',
        label: 'Confirmation recording',
        kind: 'select',
        when: (x) => !!q(x).callback,
        dependsOn: ['callback'],
        opts: ['', 'Callback confirmed', 'We will call you shortly'],
      },
    ],
  },
  {
    id: 'qnotify',
    title: 'Notifications',
    sub: 'Messages sent after an inbound call.',
    fields: [
      {
        id: 'smsReceived',
        label: 'SMS — call answered (caller)',
        kind: 'select',
        opts: ['', 'Thanks for calling', 'Ticket raised'],
        cmp: 'smsReceived',
      },
      {
        id: 'smsMissedCaller',
        label: 'SMS — call missed (caller)',
        kind: 'select',
        opts: ['', 'Sorry we missed you', 'Call us back'],
      },
      {
        id: 'smsMissedAgent',
        label: 'SMS — call missed (agent)',
        kind: 'select',
        opts: ['', 'Missed queue call alert'],
      },
      {
        id: 'waReceived',
        label: 'WhatsApp — call answered (caller)',
        kind: 'select',
        opts: ['', 'Thanks for calling'],
      },
      {
        id: 'waMissed',
        label: 'WhatsApp — call missed (caller)',
        kind: 'select',
        opts: ['', 'Sorry we missed you'],
      },
    ],
  },
  {
    id: 'qreport',
    title: 'Reporting',
    sub: 'How this queue is measured.',
    fields: [
      {
        id: 'sla',
        label: 'SLA duration (sec)',
        kind: 'number',
        help: 'Calls answered inside this window count as within SLA.',
      },
    ],
  },
];

export const QUEUE_TIERS: Array<1 | 2 | 3> = [1, 2, 3];

export function newQueue(id: string, name = ''): InboundQueue {
  return {
    id,
    name,
    desc: '',
    dids: [],
    strategy: 'Longest wait time',
    queueTimeout: '90',
    agentRingTimeout: '30',
    transferCode: '',
    intercomId: '',
    failoverDest: 'Hangup',
    failoverMusic: '',
    sticky: 'No',
    stickyTimeFormat: '',
    stickyFailover: '',
    stickyFailoverRec: '',
    welcome: '',
    moh: '',
    waitAnnounce: false,
    waitRec: '',
    positionAnnounce: false,
    positionRec: '',
    queueLimit: false,
    maxCallers: '',
    limitAction: 'Hangup',
    repeatCaller: false,
    repeatDays: '',
    smsReceived: '',
    smsMissedCaller: '',
    smsMissedAgent: '',
    waReceived: '',
    waMissed: '',
    agents: [],
    priority: false,
    tiers: {},
    callback: false,
    threshold: '30',
    dtmf: '',
    thresholdRec: '',
    hangupRec: '',
    sla: '',
  };
}
